name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: Release
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release)') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: FerrLabs/FerrFlow@96fe796ae080e72d5f5190112f251182c924999b # v7.26.3
        with:
          version: '7.26.3'
          bot: true
